### ISSUE TITLE
Setting up Jenkins with configuration from SCM

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#1]
# Acceptance Criteria

* [x] Can run jenkins locally by reading documentation only
* [X] There is a repository for jenkins configuration
* [x] The UI in jenkins does not allow modifications unless logged in
* [x] The UI in jenkins allows access to anyone for viewing

# Tasks
- [X] Create a new repository in the ipfs organization
- [x] Put the initial configuration
    - [x] read-only UI
- [x] Documentation about running dev environment
# Dependencies

**Comment by victorb** [comment]
@lgierth @Kubuxu you want to confirm that this story is done? Should be able to start jenkins locally from following the instructions in the readme.

**Comment by Kubuxu** [comment]
LGTM

**Comment by ghost** [comment]
LVGTM

edit: `Finished: SUCCESS`

**Comment by victorb** [comment]
Sweet! First task in our sprint done! Let's go party! 🌞
