### ISSUE TITLE
Running jenkins with HTTPS

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#16]
## Acceptance Criteria

- [ ] Access jenkins via https://ci.ipfs.team
- [ ] Certificate is valid
- [ ] Navigating to http://ci.ipfs.team should redirect to https://ci.ipfs.team

## Tasks

- [x] Run production jenkins on other port than :80
- [x] Deploy nginx + config on jenkins host
- [x] Setup nginx to proxy requests to running jenkins container
- [ ] Setup Let's Encrypt

## Dependencies

Depends on #8 

## Notes

Currently, I think we have a "catch-all" configuration in ipfs/infrastructure for nginx, where the certificate for ipfs.io is applied to all domains. We have the same issue when navigating to https://beta.ipld.io and ipfs.io certificate is showing up...

**Comment by ghost** [comment]
Nginx wiring is done in ipfs/infrastructure#237, https is todo.
