### ISSUE TITLE
Setting up monitoring/alerts

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#2]
# Acceptance Criteria

* [x] Can view jenkins monitoring dashboards
* [x] Can deploy changes to monitoring by reading the documentation
* [x] Will get alerts if certain metrics goes under the threshold

# Tasks

- [x] checkout Prometheus integration for jenkins and apply if possible
- [x] Connect to existing Prometheus deployment
- [x] Setup dashboard
- [x] Setup alerts

# Dependencies

Depends on #1

**Comment by ghost** [comment]
Remember what this means?
> - Can check out the monitoring dashboards

Can *view* the monitoring dashboard? Or: can run the dashboard *locally*, in an automated way?

**Comment by victorb** [comment]
@lgierth my intention was "can view the monitoring dashboard".

Thinking about it now, we should probably have two tasks, one for being able to run monitoring locally and one for having it working in production. What you think?

**Comment by ghost** [comment]
Yeah let that running-locally be separate: ipfs/infrastructure#52

**Comment by victorb** [comment]
Ok, in that case, this task would depend on us running jenkins deployed somewhere before you can start working on this task. Correct?

**Comment by ghost** [comment]
Nah I can get started with the local jenkins

**Comment by ghost** [comment]
#11 enables the scraping endpoint for prometheus, and the dashboard is here: http://metrics.ipfs.team/dashboard/db/jenkins?from=now-1h&to=now -- I simply imported the one from [grafana.net](https://grafana.net/dashboards/306) and I'm not very convinced by it.

The dashboard will need tuning when there's actual jobs to monitor :) And that's also when we can start setting alert conditions.

Prometheus is currently set to scrape `[fce3:5702:8051:3e65:3a36:1299:c458:1470]:8090/prometheus` and we can change that to what comes out of #8.

**Comment by ghost** [comment]
I'm wrapping this up with ipfs/infrastructure#235 which makes all provsn units systemd-compatible, so that we now also get host metrics (cpu, ram, io).

The dashboard should start showing numbers tomorrow when @VictorBjelkholm brings jenkins back up (I broke it). Over the rest of the sprint we'll tune the dashboard and add alerts as we see fit.

**Comment by ghost** [comment]
Splitting off tuning and alerting to #31.

**Comment by victorb** [comment]
Moved infrastructure for jenkins and monitoring is not setup yet. Reopening this in the meantime.

**Comment by victorb** [comment]
Yay, jenkins monitoring dashboard is back online!

![image](https://user-images.githubusercontent.com/459764/35408557-db2f2106-020f-11e8-8fc4-b4e78267f7da.png)
