### ISSUE TITLE
Simulate failures of the Testing Infrastructure

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#3]
# Description

To make sure we can quickly restart jenkins and workers, and that the alerts are working, we'd like to have simulated failures we can use as testing.

# Acceptance Criteria

* [ ] Can simulate failure easily
* [ ] Simulated failures happens on a regular interval
* [ ] When failures happen, we get alerted

# Tasks

- [ ] Find way to kill Jenkins master
- [ ] Find way to kill workers one-per-one or randomly
- [ ] Decide interval of simulated failures
- [ ] Make sure that alerts are triggered
- [ ] Be able to simulate different failures
  - [ ] Full hdd
  - [ ] Was OOM killed
  - [ ] (Random process kill?)
  - [ ] Loosing connectivity with internet backbone

# Dependencies

Depends on #1 
Depends on #2 
Depends on #8

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#76
