### ISSUE TITLE
Allow to stop builds for users allowed to start them

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#30]
# Acceptance Criteria
- [ ] As a owner of a repository that runs a job in jenkins, I should be allowed to cancel those jobs
- [ ] As a contributer to a repository that runs a job in jenkins, I should be allowed to cancel those jobs
# Tasks
- [ ] Make sure Github Authentication is setup correctly for passing AC
# Notes
Original post from @Kubuxu 
> Or we can have separate group.

**Comment by VictorBjelkholm** [comment]
:+1:

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#80
