### ISSUE TITLE
Moving forward with integration

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#39]
Right now we have very basic jobs done and it would be nice to map our what's left to do and how we'll achieve this. @diasdavid @whyrusleeping @haadcode it's important for you guys to read this through and understand it since it'll impact most of your projects in one or another way.

## Current Stage - Basics

Right now we have the basics of CI setup. Jobs for unit testing go-ipfs/js-ipfs/js-ipfs-api are done and it correctly runs jobs on pushes/PRs and sets the status. You might already have come across this in some PR. At this stage, we should not put too much trust in the Jenkins results and if it's failing only in Jenkins but not anywhere else, it's probably a bug and we would love it if you could report it to us. Also, vice-versa (passing only in jenkins) is probably also a bug.

**Cards needed for moving on:**

- [ ] #4 - go-ipfs/js-ipfs/js-ipfs-api unit and integration tests
- [ ] #7 - Cross-platform workers
- [ ] #30 - Allow to stop builds for users allowed to start them
- [x] #27 - Close docker containers when Jenkins pipeline is killed 

## Next Stage - Running jobs on all PRs

Next step, once we gain some confidence that everything is all right, is to have the jenkins work integrated into all the branches and necessary repositories. At this point, Jenkins should be trustworthy and should not have any random failures or random passing.

**Cards needed for moving on:**

- [ ] #31 - Tuning of monitoring/alerting 
- [ ] #6 - Replace Teamcity/TravisCI/CircleCI with Jenkins
- [ ] #5 - Be faster than Travis on go-ipfs commit to green status 

## Final Stage - Everything disabled but Jenkins

So, when we're 100% sure everything is working, everything but Jenkins will be switched off and we will live happily ever after.

@diasdavid @whyrusleeping @haadcode any feedback is good feedback :)

**Comment by daviddias** [comment]
What's blocking this?

**Comment by victorb** [comment]
@diasdavid it's outlines in the issue body, which issues are needed for each "stage"

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#83
