### ISSUE TITLE
go-ipfs/js-ipfs/js-ipfs-api unit and integration tests

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#4]
# Acceptance Criteria

* [ ] When new commit happens in repository, jenkins should run the necessary tests and report back status to Github
* [ ] You should be able to trigger builds with specific versions of go-ipfs/js-ipfs-api to be able to test compatibility
* [x] JavaScript tests should be able to run in a browser 

# Tasks

- [x] Artifacts/Pipelines flow
- [x] JS side should be able to handle browser tests
    - [x] firefox/chrome installed on build-nodes (xvfb)
    - [x] Suitable adapters
- [ ] js-ipfs-api be able to use artifact from go-ipfs builds
- [ ] go-ipfs should be able to use artifacts from js-ipfs-api
- [x] Run tests on commit to repository
    - [x] Set build status on commit
- [x] Run tests on PR created/updated
    - [x] Set build status on PR

# Dependencies

Depends on #1

**Comment by victorb** [comment]
I'll start with adding `js-ipfs` unit tests from here.

**Comment by Kubuxu** [comment]
I think I am almost done with go-ipfs unit and sharness tests. Coverage is still pending.

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#77
