### ISSUE TITLE
Be faster than Travis on go-ipfs commit to green status

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#5]
# Description

We want our new testing infrastructure to be able to fetch, build and test faster than our existing CI service does.

# Acceptance Criteria

* [x] Making a commit/pr on go-ipfs and waiting for the commit/pr status to turn green is faster than it is on TravisCI

# Tasks

- [x] Measure time from commit to green status with Travis
- [x] Make fetching commits fast
- [x] Make building fast
- [x] Make go-ipfs test run faster
  - [ ] Avoid running things that doesn't make sense to run,
        Example: don't run coverage if tests don't pass.
- [ ] @Kubuxu to have timeboxed timeslot to figure out more tasks if necessary 

# Dependencies

Depends on #1 
Depends on #4

**Comment by Kubuxu** [comment]
I would add: `[ ] Make it easy to throw more hardware at it`

**Comment by Kubuxu** [comment]
Some other things to consider:

- testing utilities artifacts, I am quite sure we could shave off some time thanks to it.
- gx sources passthrough, maybe building source ball early and passing it through

**Comment by Kubuxu** [comment]
Other option would be to have a ipfs node on each worker/worker cluster (local network/data center) and then ipfs would be caching those gx sources.

If we had those nodes exclusively for the builds then they could be also used as listing of past and current dependencies.

**Comment by Kubuxu** [comment]
This means that we would need gx inside the build container and I would be for keeping a prebuilt version in it. This would allow us to update gx version in every repo being built very easily.

**Comment by victorb** [comment]
Thanks a lot @Kubuxu, added your points to the list of tasks
