### ISSUE TITLE
Replace Teamcity/TravisCI/CircleCI with Jenkins

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#6]
# Acceptance Criteria

- [ ] go-ipfs, js-ipfs-api and js-ipfs uses Jenkins instead of Teamcity/TraviCI and CircleCI

# Tasks
- [ ] Way of storing secrets for
    - [ ] Coverage uploading [CircleCI]
- [ ] Disable the services in Github
- [ ] Remove configuration files for services

# Dependencies

Depends on #1  
Depends on #2  
Depends on #3  
Depends on #4 
Depends on #5 
Depends on #7

**Comment by victorb** [comment]
Status update:

- js-ipfs-api is using jenkins already!
- js-ipfs has a PR pending, just a couple of windows tests are missing: https://github.com/ipfs/js-ipfs/pull/1103
- go-ipfs has a PR pending with a couple of things missing: https://github.com/ipfs/go-ipfs/pull/4430

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#78
