### ISSUE TITLE
Cross-platform workers

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#7]
# Acceptance Criteria

- [x] Tests can specify which platforms to run on and it's possible to run on:
    - [x] Linux
    - [x] OSX
    - [x] Windows

# Tasks
- [x] Configuration for workers in SCM
- [x] Deployed in production
  - [x] Linux
  - [x] OSX
  - [x] Windows

# Notes

* How to scale OSX workers?

# Dependencies

Depends on #1

**Comment by ghost** [comment]
Let's call them workers ;)

**Comment by victorb** [comment]
@lgierth fixed, thanks :)

**Comment by Kubuxu** [comment]
Other platform worth including would be `ARM` and also 32bit linux.

**Comment by dignifiedquire** [comment]
agreed on ARM, though this means adding a full matrix of devices if done properly

**Comment by Kubuxu** [comment]
@dignifiedquire I proposed ARM here because we broke builds on ARM recently (same with 32bit linux) and we are currently supporting both of those architectures.

We can add more mobile platforms in future but for now I think that CI should cover what we are providing on dist.ipfs.io

**Comment by victorb** [comment]
Yeah, ARM as a architecture makes sense to support but going full out with a device farm (for what I'm guessing is for mobile tests) is too early at this point.

**Comment by dignifiedquire** [comment]
I meant that just supporting ARM means having multiple devices as they come in different versions plus you need a single device per worker given their somewhat limited power.

**Comment by Kubuxu** [comment]
What I mean by ARM right now is ARMv7/v8 with Linux running (which is RPi and its clones, Scaleway and many of IoT.

**Comment by dignifiedquire** [comment]
I have two pis around which are entirely unused, which we could hook up.

**Comment by victorb** [comment]
Thanks for the offer! Right now, focus is on the three major platforms, then we can start planning for how to support ARM, 32bit linux, FreeBSD and other fun platforms.

**Comment by victorb** [comment]
Depends on https://github.com/ipfs/aegir/issues/159

**Comment by victorb** [comment]
Current status of this:

Managed to setup linux + windows workers via Terraform + AWS in a nice way. Doing some minor refactoring then will submit PR and later deploy it.

macOS workers are more difficult... Either set them up manually or integrate with something like vmware vSphere to create virtual workers on one or more hosts. MacStadium seems like a suitable hosts with support for this (and I've done smaller trials with hosted Mac Minis) or we go forward with #73 which can be used for virtual workers for any OS.

FYI: automating the setup of windows machines is a pita...

**Comment by victorb** [comment]
We're running cross-platform tests now!
