### ISSUE TITLE
Production jenkins deploy

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#8]
# Acceptance Criteria

* [x] Can deploy jenkins by reading documentation and having permission to deploy
* [x] No modifications can be done in the UI

# Tasks

- [x] Write deploy script for jenkins
- [x] Documentation for deploying on instance
- [x] Have instance ready 
- [x] Deployed to somewhere visible
- [X] Setup domain name

# Dependencies

Depends on #1

**Comment by victorb** [comment]
Made PR for the initial work on this: https://github.com/ipfs/jenkins/pull/12

Missing: 
- [ ] Having nginx with https proxy the requests to running jenkins instead of binding the container to :80

**Comment by victorb** [comment]
Created task for https instead: https://github.com/ipfs/jenkins/issues/16
