### ISSUE TITLE
Authentication to re-run/trigger jobs

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#9]
# Description

Since the UI will be read-only for all users in production jenkins, we'll need a way of doing authentication for our developers on the various projects so they can trigger re-runs and jobs in general when wanted

# Acceptance Criteria

* [ ] As a developer of a project, I can rerun a failed job
* [ ] As a developer on the IPFS project, I can trigger jobs

# Tasks

* [ ] Find way of storing secrets that doesn't expose them to everyone
* [ ] Apply to production jenkins  

# Dependencies

Depends on #1 
Depends on #8
